trigger: ["master"]
pr: ["master"]
schedules:
  - cron: "0 1 * * 0"
    displayName: "Sunday build"
    branches:
      include: ["master"]
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: alecmocatta/azure-pipeline-templates
      endpoint: alecmocatta

jobs:
  - template: rust.yml@templates
    parameters:
      endpoint: alecmocatta
      default:
        rust_toolchain: nightly
        rust_lint_toolchain: nightly-2020-07-12
        rust_flags: ''
        rust_features_clippy: ';aws;commoncrawl;parquet;postgres;csv;json;constellation aws commoncrawl parquet postgres csv json'
        rust_features: 'constellation aws commoncrawl parquet postgres csv json'
        rust_doc_features: 'constellation aws commoncrawl parquet postgres csv json'
        rust_target_check: ''
        rust_target_build: ''
        rust_target_run: ''
      matrix:
        windows:
          imageName: 'windows-latest'
          rust_features_clippy: ';aws;commoncrawl;parquet;postgres;csv;json;aws commoncrawl parquet postgres csv json'
          rust_features: 'aws commoncrawl parquet postgres csv json'
          rust_doc_features: 'aws commoncrawl parquet postgres csv json'
          rust_target_run: 'x86_64-pc-windows-msvc'
        mac:
          imageName: 'macos-latest'
          rust_target_run: 'x86_64-apple-darwin'
        linux0:
          imageName: 'ubuntu-latest'
          rust_target_run: 'x86_64-unknown-linux-gnu'
        # linux1:
        #   imageName: 'ubuntu-latest'
        #   rust_target_run: 'x86_64-unknown-linux-musl'

  - template: rust-n.yml@templates
    parameters:
      endpoint: alecmocatta
      default:
        rust_toolchain: stable
        rust_lint_toolchain: nightly-2020-07-12
        rust_flags: ''
        rust_features_clippy: ';aws;commoncrawl;postgres;csv;json;aws commoncrawl postgres csv json'
        rust_features: 'aws commoncrawl postgres csv json'
        rust_doc_features: 'aws commoncrawl postgres csv json'
        rust_target_check: ''
        rust_target_build: ''
        rust_target_run: ''
      matrix:
        mac:
          imageName: 'macos-latest'
          rust_target_run: 'x86_64-apple-darwin'
        linux:
          imageName: 'ubuntu-latest'
          rust_target_run: 'x86_64-unknown-linux-gnu'
        windows:
          imageName: 'windows-latest'
          rust_target_run: 'x86_64-pc-windows-msvc'

  - template: rust-n.yml@templates
    parameters:
      ordinal: 2
      endpoint: alecmocatta
      default:
        rust_toolchain: nightly
        rust_lint_toolchain: nightly-2020-07-12
        rust_flags: ''
        rust_packages: '-p amadeus-core -p amadeus-derive -p amadeus-parquet -p amadeus-serde -p amadeus-types -p amadeus'
        rust_features_clippy: ';parquet;csv;json;parquet csv json'
        rust_features: 'parquet csv json'
        rust_doc_features: 'parquet csv json'
        rust_target_check: ''
        rust_target_build: ''
        rust_target_run: ''
      matrix:
        mac:
          imageName: 'macos-latest'
          rust_target_run: 'wasm32-unknown-unknown'
        linux:
          imageName: 'ubuntu-latest'
          rust_target_run: 'wasm32-unknown-unknown'
        # TODO: headless browser fails: driver status: exit code: 1
        # windows:
        #   imageName: 'windows-latest'
        #   rust_target_run: 'wasm32-unknown-unknown'

  - template: rust-n.yml@templates
    parameters:
      ordinal: 3
      endpoint: alecmocatta
      default:
        rust_toolchain: stable nightly
        rust_lint_toolchain: nightly-2020-07-12
        rust_flags: ''
        rust_packages: '-p amadeus-core -p amadeus-derive -p amadeus-serde -p amadeus-types -p amadeus'
        rust_features_clippy: ';csv;json;csv json'
        rust_features: 'csv json'
        rust_doc_features: 'csv json'
        rust_target_check: ''
        rust_target_build: ''
        rust_target_run: ''
      matrix:
        mac:
          imageName: 'macos-latest'
          rust_target_run: 'wasm32-unknown-unknown'
        linux:
          imageName: 'ubuntu-latest'
          rust_target_run: 'wasm32-unknown-unknown'
        # TODO: headless browser fails: driver status: exit code: 1
        # windows:
        #   imageName: 'windows-latest'
        #   rust_target_run: 'wasm32-unknown-unknown'
