[workspace]

[package]
name = "amadeus"
version = "0.1.1"
license = "Apache-2.0"
authors = ["Alec Mocatta <alec@mocatta.net>"]
categories = ["concurrency","science"]
keywords = ["constellation","distributed","data-science"]
description = """
Harmonious distributed data analysis in Rust.
"""
repository = "https://github.com/alecmocatta/amadeus"
homepage = "https://github.com/alecmocatta/amadeus"
documentation = "https://docs.rs/amadeus/0.1.1"
readme = "README.md"
autotests = true
edition = "2018"

[badges]
# appveyor = { repository = "alecmocatta/amadeus" }
circle-ci = { repository = "alecmocatta/amadeus" }
#gitlab = { repository = "alecmocatta/amadeus" }
travis-ci = { repository = "alecmocatta/amadeus" }

maintenance = { status = "actively-developed" }

[dependencies]
amadeus_derive = { version = "0.1.0", path = "amadeus_derive" }
chrono = "0.4"
constellation-rs = { version = "0.1", git = "https://github.com/alecmocatta/constellation" }
# constellation-rs = { version = "0.1", path = "../deploy" }
crossbeam-channel = "0.3"
csv = "1.0"
either = "1.5"
flate2 = "1.0"
futures = "0.1"
fxhash = "0.2"
http = "0.1"
linked-hash-map = "0.5"
nom = "5.0"
owned_chars = "0.3"
amadeus-parquet = { git = "https://github.com/alecmocatta/amadeus-parquet", branch = "initial" } # parquet = { path = "../arrow/rust/parquet" }
postgres = { version = "0.15", features = ["with-chrono"] }
postgres-binary-copy = "0.5"
postgres-derive = "0.3"
rand = "0.7"
replace_with = "0.1"
reqwest = "0.9"
reqwest_resume = "0.2"
rusoto_core = "0.40"
rusoto_s3 = "0.40"
serde = { version = "1.0", features = ["derive"] }
serde_closure = { version = "0.1" } #, path = "../serde_closure" }
serde_derive = "1.0"
serde_json = "1.0"
serde_traitobject = { version = "0.1.3" } #, path = "../serde_traitobject" }
streaming_algorithms = { version = "0.1", git = "https://github.com/alecmocatta/streaming_algorithms" }#, path = "../streaming_algorithms" }
sum = { version = "0.1", features = ["serde"] }
url = { version = "2.1", features = ["serde"] }
walkdir = "2.2"
warc_parser = { path = "../../warc_nom_parser" }# git = "https://github.com/alecmocatta/warc_nom_parser" }

# pin; broken for some reason
bincode = "=1.0.1"

[dev-dependencies]
select = "0.4"

[profile.release]
debug = 2

[[test]]
name = "into_dist_iter"
harness = false

[[test]]
name = "panic"
harness = false
test = false # TODO

[[test]]
name = "threads"
harness = false

[[test]]
name = "source"
harness = false

[[test]]
name = "parquet"
harness = false

[[test]]
name = "csv"
harness = false

[[test]]
name = "json"
harness = false

[[test]]
name = "postgres"
harness = false
