[package]
name = "amadeus-serde"
version = "0.1.0"
license = "Apache-2.0"
description = "Derive Macro TODO"
homepage = "https://github.com/alecmocatta/amadeus"
repository = "https://github.com/alecmocatta/amadeus"
authors = ["..."]
keywords = [ "arrow", "parquet", "hadoop" ]
readme = "README.md"
edition = "2018"

[dependencies]
amadeus-core = { version = "0.1", path = "../amadeus-core" }
amadeus-types = { version = "0.1", path = "../amadeus-types" }
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.2"
serde_json = "1.0"
csv = "1.0"
chrono = { version = "0.4", features = ["serde"] }
linked-hash-map = "0.5"
serde_closure = { version = "0.1" } #, path = "../serde_closure" }
sum = { version = "0.1", features = ["serde"] }
