[package]
name = "amadeus-aws"
version = "0.1.0"
license = "Apache-2.0"
description = "Derive Macro TODO"
homepage = "https://github.com/alecmocatta/amadeus"
repository = "https://github.com/alecmocatta/amadeus"
authors = ["..."]
keywords = [ "arrow", "parquet", "hadoop" ]
readme = "README.md"
edition = "2018"

[dependencies]
amadeus-core = { version = "0.1", path = "../amadeus-core" }
chrono = "0.4"
flate2 = "1.0"
futures-01 = { package = "futures", version = "0.1" }
futures-preview = { version = "=0.3.0-alpha.18", features = ["compat"] }
http = "0.1"
once_cell = "1.0"
rusoto_core = "0.40"
rusoto_s3 = "0.40"
serde_closure = "0.1"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1.7"
url = { version = "2.1", features = ["serde"] }
